AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3Bucket:
    Type: String
    Description: S3Bucket.
  S3Key:
    Type: String
    Default: aws-lambda-example.jar
    Description: S3Key.
Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: example
      Code:
        S3Bucket: !Ref 'S3Bucket'
        S3Key: !Ref 'S3Key'
      Handler: jp.pigumer.lambda.Handler::handle
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: java8
  LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: LambdaExecutionRole
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: /
        Policies:
        - PolicyName: root
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - "logs:*"
              Resource: "arn:aws:logs:*:*:*"
Outputs:
  LambdaExecutionRole:
    Value: !Ref 'LambdaExecutionRole'
    Export:
      Name: LambdaExecutionRole